### PR TITLE
Update to 1.15.4

### PR DESCRIPTION
**Pull request by akabanovs**
- sha256 changed
- param pinned to 1.8.2 in host requirements
- build already 0

### CODE REVIEW

**Comment by jlstevens** [comment]
I'm not aware of any reason param needs to be pinned to 1.8.2 here. Would removing that fix the lint error?

**Review by skupr-anaconda — APPROVED** [review]

**Comment by jlstevens** [comment]
@akabanovs Looks good to me if the linter error isn't an issue!

**Comment by akabanovs** [comment]
@jlstevens linter error seems not to cause any issues. It is just suggesting to pin packages in the host file, but not all of them require pinning.  I am new to packaging but I have learned that it is good practice to pin those packages in the host which also appear under run requirements, to the lowest version.

**Comment by jlstevens** [comment]
I'm also just wondering, is this syntax valid?

```yml
- param 1.9.3
```

I've never seen pins done like this before! Shouldn't it be:

```yml
- param=1.9.3
```

?

**Comment by akabanovs** [comment]
@jlstevens It actually works either way. Both will be interpreted as exact version pining.

**Review by ELundby45 — APPROVED** [review]
LGTM!

**Pull request merged**
