### PR TITLE
Update to 1.17.1

### PR DESCRIPTION
**Pull request by jlstevens**
Simple pull request matching the update on [conda-forge](https://github.com/conda-forge/holoviews-feedstock/pull/96)

### CODE REVIEW

**Review by skupr-anaconda — APPROVED** [review]
LGTM

**Review by lorepirri — COMMENTED** [review]
1. in host section: `param 1.13.0` and `pyct 0.5.0`
1. please remove:
    ```
      skip-lints:
        - python_build_tool_in_run
        - host_section_needs_exact_pinnings
    ```
    because `host_section_needs_exact_pinnings` is fixed in the first point above and `python_build_tool_in_run` is a warning that will be handled better in next versions of `linter`

1. `matplotlib-base` in `run` seems a dev dep, I think it could be removed, and it seems not used in the code but only by `pyct`:
https://github.com/holoviz/holoviews/blob/e2f06d08c3a255b83dabca42dc6636e888360225/setup.cfg#L9

**Review by lorepirri — APPROVED** [review]

**Review by philippjfr — APPROVED** [review]

**Comment by philippjfr** [comment]
>matplotlib-base in run seems a dev dep, I think it could be removed, and it seems not used in the code but only by pyct:

We have in the past always had matplotlib(-base) as a hard dependency for HoloViews on conda. We might revisit this decision but probably not in a micro-release.

**Comment by lorepirri** [comment]
> > matplotlib-base in run seems a dev dep, I think it could be removed, and it seems not used in the code but only by pyct:
> 
> We have in the past always had matplotlib(-base) as a hard dependency for HoloViews on conda. We might revisit this decision but probably not in a micro-release.

got it, thanks

**Pull request merged**
