### PR TITLE
Update to 1.17.0

### PR DESCRIPTION
**Pull request by jlstevens**
Simple version bump to 1.17.0 - I simply followed the changes in the conda-forge feedstock.

### CODE REVIEW

**Review by SC426 — APPROVED** [review]

**Comment by rafaelmartins** [comment]
It seems that this package now requires python 3.8: https://github.com/holoviz/holoviews/blob/v1.17.0/setup.py#L157

**Review by SC426 — COMMENTED** [review]
Yes, good catch @rafaelmartins. You do need to change line 15 to `py<38`
https://github.com/holoviz/holoviews/blob/f73e703f7885b6164d772337be5374a8ddae5d36/setup.py#L157

**Review by skupr-anaconda — APPROVED** [review]
LGTM but comments should be addressed

**Comment by jlstevens** [comment]
Looks like that comment was addressed. Ready to merge?

**Pull request merged**
