### PR TITLE
Update holoviews-1.14.5

### PR DESCRIPTION
**Pull request by ansthomas**
Added dependencies from upstream setup.py.

https://github.com/holoviz/holoviews/blob/master/setup.py (run)

https://github.com/holoviz/holoviews/blob/master/pyproject.toml (host)

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
Upstream setup.py has `panel >=0.8.0` for tag `v1.14.5 `https://github.com/holoviz/holoviews/blob/b7d7a1b10cd21a1be2dbe8bae1960ee92d785c31/setup.py#L17
Maybe, panel >=0.9.5 is for a development or the next release (the `master` branch)

**Comment by jlstevens** [comment]
Looks good to me!

I suspect panel >=0.9.5 is a higher pin for our next release (2.0) while >=0.8.0 is correct for 1.14.5 (which was a hotfix release).

Would you like me to go ahead and merge?

**Comment by philippjfr** [comment]
>Maybe, panel >=0.9.5 is for a development or the next release (the master branch)

Hmm, yeah HoloViews should **not** be pinning to Panel >=0.9.5 yet since that requires Python 3 and we still want to support Python 2 in HoloViews for now. We are now working towards HoloViews 2.0 which will require a more recent Panel version (and therefore Python 3).

**Comment by ansthomas** [comment]
Thank you so much for the review. I will merge it

**Pull request merged**
